// When a new game is started, the activeTileDistribution will be
// set equal to the tileDistribution array.
const tileDistribution = [
    "A", "A", "A", "A", "A", "A", "A", "A", "A",
    "B", "B",
    "C", "C",
    "D", "D", "D", "D",
    "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E",
    "F", "F",
    "G", "G", "G",
    "H", "H",
    "I", "I", "I", "I", "I", "I", "I", "I", "I",
    "J",
    "K",
    "L", "L", "L", "L",
    "M", "M",
    "N", "N", "N", "N", "N", "N",
    "O", "O", "O", "O", "O", "O", "O", "O",
    "P", "P",
    "Q",
    "R", "R", "R", "R", "R", "R",
    "S", "S", "S", "S",
    "T", "T", "T", "T", "T", "T",
    "U", "U", "U", "U",
    "V", "V",
    "W", "W",
    "X",
    "Y", "Y",
    "Z",
    "_", "_",
];

// This array will grow and shrink according to which pieces are in play
// by the user. 
var activeTileDistribution = [
    "A", "A", "A", "A", "A", "A", "A", "A", "A",
    "B", "B",
    "C", "C",
    "D", "D", "D", "D",
    "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E",
    "F", "F",
    "G", "G", "G",
    "H", "H",
    "I", "I", "I", "I", "I", "I", "I", "I", "I",
    "J",
    "K",
    "L", "L", "L", "L",
    "M", "M",
    "N", "N", "N", "N", "N", "N",
    "O", "O", "O", "O", "O", "O", "O", "O",
    "P", "P",
    "Q",
    "R", "R", "R", "R", "R", "R",
    "S", "S", "S", "S",
    "T", "T", "T", "T", "T", "T",
    "U", "U", "U", "U",
    "V", "V",
    "W", "W",
    "X",
    "Y", "Y",
    "Z",
    "_", "_",
];

// For testing purposes:
// var tileDistribution = [
//     "A",
//     "B",
//     "C",
//     "D",
//     "E",
//     "_", "_",
// ];

var tileFile = {
    "A" : "Scrabble_Tile_A.jpg",
    "B" : "Scrabble_Tile_B.jpg",
    "C" : "Scrabble_Tile_C.jpg",
    "D" : "Scrabble_Tile_D.jpg",
    "E" : "Scrabble_Tile_E.jpg",
    "F" : "Scrabble_Tile_F.jpg",
    "G" : "Scrabble_Tile_G.jpg",
    "H" : "Scrabble_Tile_H.jpg",
    "I" : "Scrabble_Tile_I.jpg",
    "J" : "Scrabble_Tile_J.jpg",
    "K" : "Scrabble_Tile_K.jpg",
    "L" : "Scrabble_Tile_L.jpg",
    "M" : "Scrabble_Tile_M.jpg",
    "N" : "Scrabble_Tile_N.jpg",
    "O" : "Scrabble_Tile_O.jpg",
    "P" : "Scrabble_Tile_P.jpg",
    "Q" : "Scrabble_Tile_Q.jpg",
    "R" : "Scrabble_Tile_R.jpg",
    "S" : "Scrabble_Tile_S.jpg",
    "T" : "Scrabble_Tile_T.jpg",
    "U" : "Scrabble_Tile_U.jpg",
    "V" : "Scrabble_Tile_V.jpg",
    "W" : "Scrabble_Tile_W.jpg",
    "X" : "Scrabble_Tile_X.jpg",
    "Y" : "Scrabble_Tile_Y.jpg",
    "Z" : "Scrabble_Tile_Z.jpg",
    "_" : "Scrabble_Tile_Blank.jpg",
}

var alpha = [
    "A", "B", "C", "D", "E",
    "F", "G", "H", "I", "J",
    "K", "L", "M", "N", "O",
    "P", "Q", "R", "S", "T",
    "U", "V", "W", "X", "Y",
    "Z", "_",
]